version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    user: root
    networks:
      - devops-net

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
    environment:
      SONARQUBE_JDBC_USERNAME: admin
      SONARQUBE_JDBC_PASSWORD: threepoints
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    networks:
      - devops-net

volumes:
  jenkins_home:

networks:
  devops-net:
    driver: bridge